name: Build Angular App

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a stable version of Node.js

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build --if-present

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: angular-dist
          path: dist/
